### ISSUE TITLE
Searching in range does not return hits ( start, length, nWord )

### ISSUE THREAD

**Issue by kmsheng** [ksanaforge/ksana-simple-api#4]
https://github.com/karmapa17/jiangkangyur/blob/master/test/test-filterbyrange.js

**Comment by kmsheng** [comment]
@yapcheahshen 請問這個 issue 的進度是 ?

**Comment by yapcheahshen** [comment]
2016年1月19日 上午10:11

因為filter 不抓內文(很慢)，所以還是 real vpos 的hits，
有內文，才有辦計轉換為真實的text offsets。

因為 highlight 一定要有內文，所以real hits 在ksa.fetch階段才產生。

**Comment by kmsheng** [comment]
@yapcheahshen 我不太懂你意思, 所以是要拿 filter 出來的 uti 重新餵給 ksa.fetch 嗎 ?

**Comment by kmsheng** [comment]
@yapcheahshen 這個 issue 要的功能等同於 keyboard search, 只是範圍限制在一個 sutra, 我還是要有 hits 才可以塗紅啊

**Comment by yapcheahshen** [comment]
要有內文才算得出real hits
ksa.filter 不抓內文。

kmsheng notifications@github.com 於 2016年1月21日 下午8:53 寫道：

**Comment by kmsheng** [comment]
@yapcheahshen 建議你的 function 可以設計成有選項的使用方式, 讓使用者決定要不要載入內文跟 hits, 像現在這樣要讓使用者自行 call 多個 function 然後再合併 result sets 是非常不直覺的。

**Comment by kmsheng** [comment]
@yapcheahshen 命名的一致性也是, 同樣的 property hits 在 ksa.fetch 是塗紅用的, 到了 ksa.filter 就變 real vpos 的 hits ???

**Comment by yapcheahshen** [comment]
ksana-simple-api@1.5.19
ksa.toc 和ksa.filter 返回vhits
yap

2016-01-21 22:47 GMT+08:00 kmsheng notifications@github.com:
